### ISSUE TITLE
卡在登录界面

### ISSUE THREAD

**Issue by Lebhoryi** [AnTi-anti/damai_ticket#1]
###打开浏览器，进入大麦网###
###请点击登录###
###请扫码登录###
###Cookie保存成功###
###成功获取Cookie，重启浏览器###
###开始登录###
###载入Cookie###
***错误：登录失败,请删除cookie后重试***

用的是扫码登陆，楼主方便再实验一下么

**Comment by Lebhoryi** [comment]
![image](https://user-images.githubusercontent.com/28487306/124493993-df186080-dde8-11eb-8df2-9dcf018f3bb2.png)

卡在这一行代码

**Comment by qq2455141515** [comment]
###打开浏览器，进入大麦网###
###请点击登录###
###请扫码登录###
###Cookie保存成功###
###成功获取Cookie，重启浏览器###
###开始登录###
###载入Cookie###
***错误：登录失败,请删除cookie后重试***

和楼上一样

**Comment by AnTi-anti** [comment]
首先确保Chromedrive的路径是否已经导入到config,json文件中

**Comment by AnTi-anti** [comment]
> ![image](https://user-images.githubusercontent.com/28487306/124493993-df186080-dde8-11eb-8df2-9dcf018f3bb2.png)
> 
> 卡在这一行代码

首先确保Chromedrive的路径是否已经导入到config,json文件中

**Comment by Anjuice666** [comment]
***错误：登录失败,请删除cookie后重试***  driver_path也正确加进去了
