### ISSUE TITLE
启动报错

### ISSUE THREAD

**Issue by Yan-minghao** [AnTi-anti/damai_ticket#10]
![image](https://user-images.githubusercontent.com/33973209/145506622-9bec36d9-7147-4ab4-834b-8663f262a1f9.png)

/usr/local/bin/python3.8 "/Users/ymh_sirius/Library/Application Support/JetBrains/Toolbox/apps/PyCharm-P/ch-0/213.5744.248/PyCharm.app/Contents/plugins/python/helpers/pydev/pydevd.py" --multiproc --qt-support=auto --client 127.0.0.1 --port 50333 --file /Users/ymh_sirius/001_File/002code/python/github/AnTi-anti/damai_ticket/damai_ticket.py
Connected to pydev debugger (build 213.5744.248)
Unexpected UTF-8 BOM (decode using utf-8-sig): line 1 column 1 (char 0)

Process finished with exit code 1

**Comment by lorenshan** [comment]
用notepad++保存成UTF-8无BON
