### ISSUE TITLE
提示实名信息选择框没有显示

### ISSUE THREAD

**Issue by cwbkobe** [AnTi-anti/damai_ticket#11]
###进入抢票界面###
###请自行选择位置和票价###
###等待--确认订单--页面出现，可自行刷新，若长期不跳转可选择-- CRTL+C --重新抢票###
***Error：实名信息选择框没有显示***

以上为日志信息，对应的测试网址是：https://detail.damai.cn/item.htm?id=663344287202

**Comment by Lecxxx** [comment]
同问

**Comment by Lecxxx** [comment]
check_order函数中的if else中的else改成
else:
sleep(0.5)
self.driver.find_element_by_xpath('/html/body/div[3]/div[2]/div/div[8]/button').click()
json文件中的real_name填null
这是不用选观影人的时候的用法
