### ISSUE TITLE
实名信息选择框没有显示

### ISSUE THREAD

**Issue by lorenshan** [AnTi-anti/damai_ticket#12]
###进入抢票界面###
###请自行选择位置和票价###
###等待--确认订单--页面出现，可自行刷新，若长期不跳转可选择-- CRTL+C --重新抢票###
***Error：实名信息选择框没有显示***

测试页https://detail.damai.cn/item.htm?spm=a2oeg.home.card_0.ditem_1.591b23e1poMmG7&id=662714525721

**Comment by Lecxxx** [comment]
改成这样就好 real_name填null
![image](https://user-images.githubusercontent.com/49981610/159887365-713dff71-897f-4c9b-9105-2f2c9efd512b.png)

**Comment by Lecxxx** [comment]
check_order函数中的if else中的else改成
else:
sleep(0.5)
self.driver.find_element_by_xpath('/html/body/div[3]/div[2]/div/div[8]/button').click()
json文件中的real_name填null
这是不用选观影人的时候的用法
