### ISSUE TITLE
下单页面出现频繁弹框

### ISSUE THREAD

**Issue by oneAsiaPeople** [AnTi-anti/damai_ticket#17]
经过测试 使用js代码隐藏弹窗之后可以 直接下单  这个我本地已经改好

**Comment by AlanHN** [comment]
@demonlov 大佬求代码

**Comment by demonlov** [comment]
`  

                    tb = WebDriverWait(self.driver, 1, 0.1).until(
                        EC.presence_of_element_located((By.XPATH, '/html/body/div[3]/div[2]/div')))

                    if len(tb.find_elements_by_xpath("//div[@class='baxia-dialog-content']/.."))> 0:

                        print("开始清除遮罩")
                        WebDriverWait(self.driver, 1, 0.1).until(
                            EC.presence_of_element_located((By.XPATH, "//div[@class='baxia-dialog-content']/..")))
                        print(
                            tb.find_elements_by_xpath("//div[@class='baxia-dialog-content']/..")[0].get_attribute(
                                "class"))
                        remove_class = tb.find_elements_by_xpath("//div[@class='baxia-dialog-content']/..")[
                            0].get_attribute("class")
                        js = f'document.getElementsByClassName("{remove_class}")[0].style.display="none"'
                        self.driver.execute_script(js)
                        print("遮罩清除成功！")
 `

**Comment by demonlov** [comment]
> 
我贴了一些代码片段 是否能帮助到你

**Comment by AlanHN** [comment]
很有帮助，非常感谢🙏

**Comment by wty666999** [comment]
> 经过测试 使用js代码隐藏弹窗之后可以 直接下单 这个我本地已经改好

前辈，您好，使用您的代码将滑块弹窗去除之后，一直没能跳转到支付宝的付款界面，请问您有什么好的建议吗？
