### ISSUE TITLE
开头就报错

### ISSUE THREAD

**Issue by Dr34nn** [AnTi-anti/damai_ticket#2]

**Comment by Alost1** [comment]
Unexpected UTF-8 BOM (decode using utf-8-sig): line 1 column 1 (char 0)

**Comment by AnTi-anti** [comment]
> Unexpected UTF-8 BOM (decode using utf-8-sig): line 1 column 1 (char 0)

#coding:utf-8

**Comment by ouyangjunfei** [comment]
好像是 config.json 文件二进制的问题，删除然后新建一次就可以了，Win10 GBK平台

@AnTi-anti @Alost1

**Comment by Mrfuhang** [comment]
with open('./config.json', 'r', encoding='utf-8-sig') as f:
            config = loads(f.read())  
    这样就行了
