### ISSUE TITLE
登录出现报错

### ISSUE THREAD

**Issue by LAOYISHUJIA** [AnTi-anti/damai_ticket#22]
![微信图片_20220805214226](https://user-images.githubusercontent.com/110675040/183089784-f766fccc-bd3c-42bb-9bf1-fb98e6f78a99.jpg)
这个由于版本更新，代码使用方法过时出现的报错有无办法解决？

**Comment by Anjuice666** [comment]
> ![微信图片_20220805214226](https://user-images.githubusercontent.com/110675040/183089784-f766fccc-bd3c-42bb-9bf1-fb98e6f78a99.jpg) 这个由于版本更新，代码使用方法过时出现的报错有无办法解决？

`from selenium.webdriver.chrome.service import Service
...
s = Service(self.driver_path)
        self.driver = webdriver.Chrome(service=s, options=options, desired_capabilities=capa)`
