### ISSUE TITLE
***Error: 实名制遮罩关闭失败***

### ISSUE THREAD

**Issue by nieyishiye** [AnTi-anti/damai_ticket#23]
小白刚入门 这个是啥情况 谢谢大佬！
***Error: 实名制遮罩关闭失败***

**Comment by megumi-taffy** [comment]
代码在这里，不知道什么问题
 try:
                realname_popup = box.find_elements_by_xpath("//div[@class='realname-popup']")  # 寻找实名身份遮罩
                if len(realname_popup) != 0:
                    known_button = realname_popup[0].find_elements_by_xpath("//div[@class='operate']//div[@class='button']")
                    known_button[0].click()
            except:
                raise Exception(u"***Error: 实名制遮罩关闭失败***")

**Comment by AnTi-anti** [comment]
> 

元素定位失败

**Comment by WonderDing** [comment]
把raise Exception(u"Error: 实名制遮罩关闭失败")注释掉试试，应该是查找实名身份遮罩失败了，或者没有弹出遮罩
