### ISSUE TITLE
跪求大佬尽快更新能移动端抢票的代码

### ISSUE THREAD

**Issue by peppaaaaaaaa** [AnTi-anti/damai_ticket#28]

**Comment by hjc18** [comment]
同求https://m.damai.cn/

**Comment by weixiang-xu** [comment]
一看就知道是抢杰伦票的233333，好像现在只能在APP上抢啊。

**Comment by whalucard** [comment]
同求大佬
楼上的杰迷们好啊
刚刚抢完太原两场均失败告终

**Comment by EDSpower** [comment]
同求大佬
楼上的杰迷们好啊
刚刚抢完太原两场均失败告终

**Comment by zxealous** [comment]
同求大佬
楼上的杰迷们好啊
刚刚抢完太原两场均失败告终

**Comment by MilesYuanCN** [comment]
试过自动化脚本，抢不过专业的牛牛们

**Comment by zzcmaple** [comment]
切换到h5是一种思路，但是在付款是还是被检测出来，作者或者大佬们有没有帮帮忙的（已经将window.navigator.webdriver变为false）

**Comment by hjc18** [comment]
> 切换到h5是一种思路，但是在付款是还是被检测出来，作者或者大佬们有没有帮帮忙的（已经将window.navigator.webdriver变为false）

确认订单时出滑块验证，手动拉滑块都会失败

**Comment by zzcmaple** [comment]
> 
是的，昨天调试已经发现了问题，因为是模拟手机浏览器，当抢票后提示了人数过多，但我并没有对这个做处理，导致程序结束了，按钮无法点击，我就手动切了下H5，被检测出来，然后cookie就用不了了
