### ISSUE TITLE
###打开浏览器，进入大麦网###  [WinError 87] 参数错误。

### ISSUE THREAD

**Issue by NicolasCxy** [AnTi-anti/damai_ticket#30]
![image](https://user-images.githubusercontent.com/26478885/222891204-9f038ec0-f17a-4e6c-ae4e-407137e589d0.png)
大佬、这是什么情况啊？
这是我的配置文件
![image](https://user-images.githubusercontent.com/26478885/222891232-cd961291-af17-4841-9d0b-7c056806eab1.png)

**Comment by WonderDing** [comment]
同样的错误

**Comment by slimanp** [comment]
这个错误基本都是因为driver_path没填或者是填错了

**Comment by WonderDing** [comment]
> 这个错误基本都是因为driver_path没填或者是填错了

"driver_path": "C:\\Users\\**\\Downloads\\chromedriver_win32\\chromedriver.exe"对。加了之后就好了，多谢老哥
