### ISSUE TITLE
***错误：登录失败,请删除cookie后重试***

### ISSUE THREAD

**Issue by NicolasCxy** [AnTi-anti/damai_ticket#31]
![image](https://user-images.githubusercontent.com/26478885/222895042-97ab39b3-f27a-4556-8147-c1ef48148973.png)
这是什么情况？

**Comment by Mrfuhang** [comment]
我跟你的一样  登录失败 代码失效了？

**Comment by Anjuice666** [comment]
请问解决了吗  也是一样

**Comment by Anjuice666** [comment]
> 这个是它的代码抓用户名的Xpath错误，你自己上大麦网的网站，用F12抓用户名的Xpath自己填上去就好了

感谢回复，确实是这个问题，发现chromedriver打开的网页和自己用的google网页的元素不一样，用这个就好了
`locator = (By.XPATH, "/html/body/div[2]/div/div[3]/div[1]/a[2]/div")`
