### ISSUE TITLE
接口异常退出

### ISSUE THREAD

**Issue by slimanp** [AnTi-anti/damai_ticket#32]
运行起来一直循环，网页上是一闪而过的跳转到了选座页面，但是提示接口异常退出，然后又刷新回到了抢票页面。
![image](https://user-images.githubusercontent.com/48610831/223298899-0b3d7ca9-a4d5-4cdf-8383-306f0176ae32.png)

**Comment by Anjuice666** [comment]
> 运行起来一直循环，网页上是一闪而过的跳转到了选座页面，但是提示接口异常退出，然后又刷新回到了抢票页面。 ![image](https://user-images.githubusercontent.com/48610831/223298899-0b3d7ca9-a4d5-4cdf-8383-306f0176ae32.png)

请问你有遇到***错误：登录失败,请删除cookie后重试*** 咋解决的吗？

**Comment by slimanp** [comment]
> 

这个是它的代码抓用户名的Xpath错误，你自己上大麦网的网站，用F12抓用户名的Xpath自己填上去就好了
