### ISSUE TITLE
请问代码是最新的吗？

### ISSUE THREAD

**Issue by aFlyBird0** [AnTi-anti/damai_ticket#35]
显示README一直在更新，但是代码两年前就没更新了

**Comment by whileGreatHair** [comment]
感觉是骗star的，代码一直没更新，对比https://github.com/Entromorgan/Autoticket/blob/master/Autoticket.py   这个代码库，代码差不多...别人很久都没更新了。
有人成功抢到了，麻烦踢踢我。

**Comment by aFlyBird0** [comment]
> 感觉是骗star的，代码一直没更新，对比https://github.com/Entromorgan/Autoticket/blob/master/Autoticket.py   这个代码库，代码差不多...别人很久都没更新了。
> 有人成功抢到了，麻烦踢踢我。

不止，我感觉大概率是为了推荐他300块的CSDN付费专栏。
两年没更新代码我可以理解，但我不能理解更新了Readme刷了项目活跃度，但是代码没变。
