### ISSUE TITLE
谷歌界面频繁刷新，像卡住了

### ISSUE THREAD

**Issue by geecheese** [AnTi-anti/damai_ticket#38]
###打开浏览器，进入大麦网###
###开始登录###
###载入Cookie###
###登录成功###
###进入抢票界面###
***Error: ticket_num_up 位置找不到***
###进入抢票界面###
***Error: ticket_num_up 位置找不到***
###进入抢票界面###
***Error: ticket_num_up 位置找不到***
###进入抢票界面###
***Error: ticket_num_up 位置找不到***
###进入抢票界面###
这是什么原因呢？

**Comment by AnTi-anti** [comment]
提示很清楚了，ticket_num_up 位置找不到，定位下这个元素位置。
