### ISSUE TITLE
手动选择位置和票价问题

### ISSUE THREAD

**Issue by RoyZhanyi** [AnTi-anti/damai_ticket#4]
有一些票需要选座购买，能不能设置自动检测哪些座位空余并且自动选择确认票款

**Comment by AnTi-anti** [comment]
可以发个购票链接我看下

**Comment by zhangle910522** [comment]
大佬   手动选择的图片不显示是啥原因

购票链接：
https://detail.damai.cn/item.htm?spm=a2oeg.search_category.0.0.f9b14d15XxfV6n&id=665141132427&clicktitle=%E3%80%90%E5%8C%97%E4%BA%AC%E3%80%91%E7%BB%B4%E4%B9%9F%E7%BA%B3%E7%BA%A6%E7%BF%B0%C2%B7%E6%96%BD%E7%89%B9%E5%8A%B3%E6%96%AF%E7%BB%8F%E5%85%B8%E9%9F%B3%E4%B9%90%26%E4%B8%96%E7%95%8C%E5%90%8D%E6%9B%B2%E6%96%B0%E6%98%A5%E4%BA%A4%E5%93%8D%E9%9F%B3%E4%B9%90%E4%BC%9A

![微信图片_20220103225547](https://user-images.githubusercontent.com/28779854/147945327-a1ca9b73-de25-46a6-95c9-cf06725ee926.png)
