### ISSUE TITLE
无法自动勾选观演人

### ISSUE THREAD

**Issue by Wsr-7** [AnTi-anti/damai_ticket#5]
{
    "sess": [1,2],
    "price": [6, 3, 4],
    "real_name": [1, 2],
    "nick_name": "xx",
    "ticket_num": 2,
    "driver_path": "C:/Program Files (x86)/Google/Chrome/Application/chromedriver.exe",
    "damai_url": "https://www.damai.cn/",
    "target_url": "https://detail.damai.cn/item.htm?xx"
}
配置如上.
每张票需要选择一个证件时,按照说明应该是以real_name配置选择第一第二个观演人.但实际上到提交订单前,每次都要需要手动选择观演人并手动点击提交订单.这里不通的话感觉脚本就没什么意义了.还是上不了赛道.
此外,手动点击提交订单后如果是下单人数较多等情况无法下单的话,脚本就停住了,不能继续前面的操作?
不知是否我操作问题

**Comment by Vg1ee** [comment]
根据页面相应速度适当调大init_sleeptime参数
